name: Build container
on:
  push:
    branches:
    - main
env:
  CONTAINER_APP_CONTAINER_NAME: weatherclusterapi
  CONTAINER_APP_NAME: weatherclusterapi-app-2023012008
  CONTAINER_APP_RESOURCE_GROUP_NAME: blazor-deployment-samples
  CONTAINER_REGISTRY_LOGIN_SERVER: mysuperfunservice.azurecr.io
  DOCKER_FILE_PATH: ./Dockerfile
  PROJECT_NAME_FOR_DOCKER: webapplication291
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: build container
      run: |
        docker buildx build --platform linux/amd64 . -t test:0.0.2
